# Site settings
title: Scott Mackinlay
email: scottmackinlay@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is a test description
baseurl: "/portfolio" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  scottmackinlay

# Build settings
markdown: kramdown
permalink: pretty
